export const FETCH_SECURITY_QUESTIONS = 'FETCH_SECURITY_QUESTIONS';
export const FILTER_SECURITY_QUESTIONS = 'FILTER_SECURITY_QUESTIONS';
export const FILTER_SECURITY_QUESTION_ONE = 'FILTER_SECURITY_QUESTION_ONE';
export const FILTER_SECURITY_QUESTION_TWO = 'FILTER_SECURITY_QUESTION_TWO';

export const USER_BASIC_DATA_EVENT_HANDLER = 'USER_BASIC_DATA_EVENT_HANDLER';
